image: gradle:jdk8

include:
  - project: davils/templates/gitlab-ci
    file: kotlin-java.yaml

variables:
  CINTEROP_ENABLED: "true"
  TESTS_ENABLED: "false"

build:
  stage: build
  script:
    - gradle clean build -x check
