[package]
name = "example"
description = "An example project."
authors = ["Davils <contact@davils.net>"]
license = "All rights reserved"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.27.0"
 
[dependencies]
libc = "0.2.167"